"""add order_index

Revision ID: bd33c0ccd00d
Revises: 2bfacda05c24
Create Date: 2026-02-28 14:19:43.354529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd33c0ccd00d'
down_revision: Union[str, Sequence[str], None] = '2bfacda05c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlistsonglink', sa.Column('order_index', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlistsonglink', 'order_index')
    # ### end Alembic commands ###
